name: Setup Postgres + Valgrind
inputs:
  postgres-version:
    description: The Postgres version to use
    default: 17
  track-origins:
    description: Track origins
    default: no
  check-ub:
    description: Check for undefined behavior (experimental)
    default: no
runs:
  using: node24
  main: index.js
  post: cleanup.js
