name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            postgres-version: 16
            track-origins: no
    steps:
      - uses: actions/checkout@v4
        with:
          repository: pgvector/pgvector

      - uses: actions/checkout@v4
        with:
          path: action
      - uses: ./action
        with:
          postgres-version: ${{ matrix.postgres-version }}
          track-origins: ${{ matrix.track-origins }}

      - run: make OPTFLAGS=""
      - run: sudo --preserve-env=PG_CONFIG make install
      - run: make installcheck
      - run: make prove_installcheck PROVE_TESTS=test/t/015_hnsw_duplicates.pl
